config/urls.py
from django.contrib import admin
from django.urls import path, include

# from . import settings  이렇게 하지 않음
from django.conf import settings
from django.conf.urls.static import static

from rooms import views as room_views

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    # path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:  # DEBUG 상태일 때(개발 상태일 때)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    print(urlpatterns)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search")
    ]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github"),
    path("login/github/callback", views.github_callback, name="github_callback"),
    path("login/kakao/", views.kakao_login, name="kakao"),
    path("login/kakao/callback", views.kakao_callback, name="kakao_callback"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignupView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete_verification"),

    ]

templates/partials/footer.html
<footer class="container mx-auto text-center py-20 border-t font-medium text-gray-500">
    <span>
        Please don't copy us.
    </span>
    <span>&copy; 2019 Nomad Coders. All rights reserved.</span>
</footer>

templates/partials/nav.html
{% load static %}

    <ul class="flex items-center text-sm font-medium h-full">
        {% if user.is_authenticated %}
            <li class="nav_link"><a href="{% url 'users:logout' %}">Log out</a></li>
        {% else %}
            <li class="nav_link"><a href="{% url 'users:login' %}">Log in</a></li>
            <li class="nav_link"><a href="{% url 'users:signup' %}">Sign up</a></li>
        {% endif %}
    </ul>

   

templates/partials/room_card.html
<div class="w-1/4 mb-10 px-2">
    
    <div class="w-auto h-64 bg-cover bg-center rounded-lg mb-2" style="background-image: url( {{room.first_photo}} );"></div>
        <a href="{% url 'rooms:detail' room.pk %}">
        <div class="flex justify-between mb-2 truncate">
        <div class="w-4/5 overflow-hidden flex">
            {% if room.host.superhost %}
                <span class="mr-2 uppercase rounded-lg font-medium text-sm border text-black border-black py-px px-1">superhost</span> 
            {% endif %}    
            <span class="text-sm  w-11/12 block truncate pr-5 text-gray-400">{{room.city}}, {{room.country.name}}</span>
        </div>
        <div>
            <span class="text-sm flex items-center">
                <i class="fas fa-star text-red-500 text-xs mr-1"></i>{{room.Rating_Reviews}}
            </span>
        </div>
    </div>
    <span class="text-black w-11/12 block truncate">
        {{room.name}}
    </span>
    </a>
</div>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github' %}" class="login_btn w-full border-2 border-gray-700  text-gray-700 mb-2 py-5 ">
        <i class="fab fa-github-alt mr-2 fa-lg"></i>
        Continue with Github
    </a>

    <a href="{% url 'users:kakao' %}" class="login_btn w-full border border-yellow-500  text-yellow-800 mb-2 py-5 bg-yellow-400 ">
        <i class="fas fa-comment mr-2 fa-lg"></i> Continue with Kakao
    </a>
    <div class="flex items-center w-full my-5">
        <div class="h-px w-full bg-gray-300 mt-1"></div>
        <span class ="text-gray-500 font-medium mx-3 text-sm">or</span>
        <div class="h-px w-full bg-gray-300 mt-1"></div>
    </div>
</div>