config/urls.py
from django.contrib import admin
from django.urls import path, include

# from . import settings  이렇게 하지 않음
from django.conf import settings
from django.conf.urls.static import static

from rooms import views as room_views

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    # path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:  # DEBUG 상태일 때(개발 상태일 때)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    print(urlpatterns)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search")
    ]

templates/base.html
<!-- {% load static %} -->
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <title>{% block title %} {% endblock title %}</title>
</head>

<body class="text-gray-800 mt-24  font-light">
    <header class ="container max-w-full flex items-center justify-between px-6 h-20 border-b border-gray-200 fixed bg-white inset-0">
        <div class ="flex items-center my-2 w-1/3">
        <a href="{% url 'core:home' %}" class="mr-5" %>
            <img class="w-8" src="{% static 'img/logo.png' %}" class="mr-6">
        </a>
    
        {% block search-bar %}
        <form method="get" action="{% url 'rooms:search' %} " class="w-9/12">
            <input class="border px-5 py-2 mt-4 rounded-sm w-full text-normal text-gray-900 placeholder-gray-600 font-medium shadow-md hover:shadow-lg transition-property: box-shadow transition duration-200 shadow focus:outline-none" name='city ' placeholder="Search by City " />
        </form>
        {% endblock search-bar %}
    </div>
        {% include "partials/nav.html" %} 

    </header>
    {% block content %} 
    {% endblock content %} 
    {% include "partials/footer.html" %}
</body>

</html>